package alvmpurchase.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Aug 08 16:48:15 BRT 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://service.purchase.alvm.alvmcyber.labes.icmc.usp.br/", name = "AlvmCyberPurchaseService")
@XmlSeeAlso({ObjectFactory.class})
public interface AlvmCyberPurchaseService {

    @WebResult(name = "AlvmCyberCheckResp", targetNamespace = "")
    @RequestWrapper(localName = "checkPrice", targetNamespace = "http://service.purchase.alvm.alvmcyber.labes.icmc.usp.br/", className = "br.usp.icmc.labes.alvmcyber.alvm.purchase.service.CheckPrice")
    @ResponseWrapper(localName = "checkPriceResponse", targetNamespace = "http://service.purchase.alvm.alvmcyber.labes.icmc.usp.br/", className = "br.usp.icmc.labes.alvmcyber.alvm.purchase.service.CheckPriceResponse")
    @WebMethod
    public alvmpurchase.client.AlvmCyberCheckPriceResponse checkPrice(
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.String clientId,
        @WebParam(name = "numberOfRobots", targetNamespace = "")
        int numberOfRobots
    );

    @WebResult(name = "AlvmCyberOfferAck", targetNamespace = "")
    @RequestWrapper(localName = "orderOffer", targetNamespace = "http://service.purchase.alvm.alvmcyber.labes.icmc.usp.br/", className = "br.usp.icmc.labes.alvmcyber.alvm.purchase.service.OrderOffer")
    @ResponseWrapper(localName = "orderOfferResponse", targetNamespace = "http://service.purchase.alvm.alvmcyber.labes.icmc.usp.br/", className = "br.usp.icmc.labes.alvmcyber.alvm.purchase.service.OrderOfferResponse")
    @WebMethod
    public alvmpurchase.client.AlvmCyberOrderOfferAck orderOffer(
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.String clientId,
        @WebParam(name = "offerCode", targetNamespace = "")
        int offerCode
    );
}
