
/*
 * 
 */

package alvmpurchase.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Aug 08 16:48:15 BRT 2013
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "AlvmCyberPurchaseServiceService", 
                  wsdlLocation = "http://localhost:9005/AlvmCyberPurchaseService?wsdl",
                  targetNamespace = "http://service.purchase.alvm.alvmcyber.labes.icmc.usp.br/") 
public class AlvmCyberPurchaseServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.purchase.alvm.alvmcyber.labes.icmc.usp.br/", "AlvmCyberPurchaseServiceService");
    public final static QName AlvmCyberPurchaseServicePort = new QName("http://service.purchase.alvm.alvmcyber.labes.icmc.usp.br/", "AlvmCyberPurchaseServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9005/AlvmCyberPurchaseService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9005/AlvmCyberPurchaseService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AlvmCyberPurchaseServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlvmCyberPurchaseServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlvmCyberPurchaseServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AlvmCyberPurchaseService
     */
    @WebEndpoint(name = "AlvmCyberPurchaseServicePort")
    public AlvmCyberPurchaseService getAlvmCyberPurchaseServicePort() {
        return super.getPort(AlvmCyberPurchaseServicePort, AlvmCyberPurchaseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlvmCyberPurchaseService
     */
    @WebEndpoint(name = "AlvmCyberPurchaseServicePort")
    public AlvmCyberPurchaseService getAlvmCyberPurchaseServicePort(WebServiceFeature... features) {
        return super.getPort(AlvmCyberPurchaseServicePort, AlvmCyberPurchaseService.class, features);
    }

}
