
/*
 * 
 */

package alvm.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Aug 08 16:44:26 BRT 2013
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "AlvmOrderServiceService", 
                  wsdlLocation = "http://localhost:9001/AlvmOrderService?wsdl",
                  targetNamespace = "http://service.order.alvm.alvmcyber.labes.icmc.usp.br/") 
public class AlvmOrderServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.order.alvm.alvmcyber.labes.icmc.usp.br/", "AlvmOrderServiceService");
    public final static QName AlvmOrderServicePort = new QName("http://service.order.alvm.alvmcyber.labes.icmc.usp.br/", "AlvmOrderServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9001/AlvmOrderService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9001/AlvmOrderService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AlvmOrderServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlvmOrderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlvmOrderServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AlvmOrderService
     */
    @WebEndpoint(name = "AlvmOrderServicePort")
    public AlvmOrderService getAlvmOrderServicePort() {
        return super.getPort(AlvmOrderServicePort, AlvmOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlvmOrderService
     */
    @WebEndpoint(name = "AlvmOrderServicePort")
    public AlvmOrderService getAlvmOrderServicePort(WebServiceFeature... features) {
        return super.getPort(AlvmOrderServicePort, AlvmOrderService.class, features);
    }

}
