
/*
 * 
 */

package pegar.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Aug 08 16:47:00 BRT 2013
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "PegarArmsServiceService", 
                  wsdlLocation = "http://localhost:9004/PegarArmsService?wsdl",
                  targetNamespace = "http://service.pegar.alvmcyber.labes.icmc.usp.br/") 
public class PegarArmsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.pegar.alvmcyber.labes.icmc.usp.br/", "PegarArmsServiceService");
    public final static QName PegarArmsServicePort = new QName("http://service.pegar.alvmcyber.labes.icmc.usp.br/", "PegarArmsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9004/PegarArmsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9004/PegarArmsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PegarArmsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PegarArmsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PegarArmsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PegarArmsService
     */
    @WebEndpoint(name = "PegarArmsServicePort")
    public PegarArmsService getPegarArmsServicePort() {
        return super.getPort(PegarArmsServicePort, PegarArmsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PegarArmsService
     */
    @WebEndpoint(name = "PegarArmsServicePort")
    public PegarArmsService getPegarArmsServicePort(WebServiceFeature... features) {
        return super.getPort(PegarArmsServicePort, PegarArmsService.class, features);
    }

}
