
/*
 * 
 */

package braco.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Aug 08 16:45:54 BRT 2013
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "BracoArmsServiceService", 
                  wsdlLocation = "http://localhost:9003/BracoArmsService?wsdl",
                  targetNamespace = "http://service.braco.alvmcyber.labes.icmc.usp.br/") 
public class BracoArmsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.braco.alvmcyber.labes.icmc.usp.br/", "BracoArmsServiceService");
    public final static QName BracoArmsServicePort = new QName("http://service.braco.alvmcyber.labes.icmc.usp.br/", "BracoArmsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9003/BracoArmsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9003/BracoArmsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BracoArmsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BracoArmsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BracoArmsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns BracoArmsService
     */
    @WebEndpoint(name = "BracoArmsServicePort")
    public BracoArmsService getBracoArmsServicePort() {
        return super.getPort(BracoArmsServicePort, BracoArmsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BracoArmsService
     */
    @WebEndpoint(name = "BracoArmsServicePort")
    public BracoArmsService getBracoArmsServicePort(WebServiceFeature... features) {
        return super.getPort(BracoArmsServicePort, BracoArmsService.class, features);
    }

}
