package braco.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Aug 08 16:45:54 BRT 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://service.braco.alvmcyber.labes.icmc.usp.br/", name = "BracoArmsService")
@XmlSeeAlso({ObjectFactory.class})
public interface BracoArmsService {

    @WebResult(name = "bracoRespMsg", targetNamespace = "")
    @RequestWrapper(localName = "hasArms", targetNamespace = "http://service.braco.alvmcyber.labes.icmc.usp.br/", className = "br.usp.icmc.labes.alvmcyber.braco.service.HasArms")
    @ResponseWrapper(localName = "hasArmsResponse", targetNamespace = "http://service.braco.alvmcyber.labes.icmc.usp.br/", className = "br.usp.icmc.labes.alvmcyber.braco.service.HasArmsResponse")
    @WebMethod
    public braco.client.BracoResponseMessage hasArms(
        @WebParam(name = "clientCode", targetNamespace = "")
        java.lang.String clientCode,
        @WebParam(name = "modelType", targetNamespace = "")
        java.lang.String modelType,
        @WebParam(name = "amount", targetNamespace = "")
        int amount
    );
}
