package gehen.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Aug 08 17:35:30 BRT 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://service.gehen.alvmcyber.labes.icmc.usp.br/", name = "GehenMobileBaseService")
@XmlSeeAlso({ObjectFactory.class})
public interface GehenMobileBaseService {

    @WebResult(name = "gehenConfMsg", targetNamespace = "")
    @RequestWrapper(localName = "checkMobileBase", targetNamespace = "http://service.gehen.alvmcyber.labes.icmc.usp.br/", className = "br.usp.icmc.labes.alvmcyber.gehen.service.CheckMobileBase")
    @ResponseWrapper(localName = "checkMobileBaseResponse", targetNamespace = "http://service.gehen.alvmcyber.labes.icmc.usp.br/", className = "br.usp.icmc.labes.alvmcyber.gehen.service.CheckMobileBaseResponse")
    @WebMethod
    public gehen.client.GehenConfirmationMessage checkMobileBase(
        @WebParam(name = "clientCode", targetNamespace = "")
        java.lang.String clientCode,
        @WebParam(name = "modelType", targetNamespace = "")
        java.lang.String modelType,
        @WebParam(name = "amount", targetNamespace = "")
        int amount
    );
}
